openapi: 3.0.0
info:
  title: Blogging platform
  description: 'blogging platform api'
  version: '1.0'
servers:
  - url: http://localhost:5000
    description: local server
paths:
  /api/v1/authentication/signup:
    $ref: ./paths/index.yaml#/Signup
components:
  schemas:
    $ref: ./schemas/index.yaml
